### ISSUE TITLE
[BUG] Scraper has stopt with scraping plenary meetings

### ISSUE THREAD

**Issue by LoganDupont** [Parliament-in-Data/Federal-Parliament-Scraper#49] opened 2022-08-21 09:24 UTC
**Describe the bug**
If we go to https://parlement.thundr.be/sessions/55/session.json you will see that the last plenary meeting is `id` 146 with `date` 2021-12-09T00:00:00

**To Reproduce**
1. Go to https://parlement.thundr.be/sessions/55/session.json
2. Click on `meetings.plenary[0]`
3. You will see the most recent plenary meeting that has been scraped (https://parlement.thundr.be/sessions/55/meetings/146.json)

**Expected behavior**
I would expect to see the most recent plenary meeting that has happened

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 103.0.2

**Smartphone (please complete the following information):**
/

**Additional context**
/

**Comment by ndossche** [comment] 2022-08-21 11:53
It seems like something in their HTML has changed which causes the scraper to break and therefore not update the data.
I'll take a look into this this afternoon.

**Comment by ndossche** [comment] 2022-08-21 17:32
It's fixed now. Most of the issues can be attributed to mistakes or strange HTML in the plenary meeting reports.
There's one FIXME remaining that I didn't manage to fix today which is also caused by a mistake in the reporting: there's a report which has missing identifier numbers for the topics.
All these mistakes are slightly infuriating tbh...
The good news is that the new data is now available and the scraper will be able to continue scraping.

**Closed as completed by ndossche** 2022-08-21 17:32 UTC
Labels: bug, important

**Comment by LoganDupont** [comment] 2022-08-21 18:24
Thank you very much for fixing the issues so quickly. I really like this relevant project!
