### ISSUE TITLE
[BUG] Scraper didn't scrape plenary meetings starting from 03/02/23

### ISSUE THREAD

**Issue by LoganDupont** [Parliament-in-Data/Federal-Parliament-Scraper#52] opened 2023-04-16 13:17 UTC
**Describe the bug**
It seems there is again an issue with the scraper. If we go to https://parlement.thundr.be/sessions/55/session.json you will see that the last plenary meeting is id 230 with date 2023-02-02T00:00:00.

**To Reproduce**
1. Go to https://parlement.thundr.be/sessions/55/session.json
2. Click on `meetings.plenary[0]`
3. You will see the most recent plenary meeting that has been scraped (https://parlement.thundr.be/sessions/55/meetings/230.json)

**Expected behavior**
I would expect to see the most recent plenary meeting that has happened

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 111.0.1

**Smartphone (please complete the following information):**
/

**Additional context**
/

**Comment by LoganDupont** [comment] 2023-05-16 19:54
Does someone already have an update about this issue?

**Comment by ndossche** [comment] 2023-05-16 19:57
I didn't yet have a look, and apparantly neither did the others
I'll try to get it fixed sometime in the next few days

**Comment by LoganDupont** [comment] 2023-05-16 20:10
Thanks for the update! No hurry, take the time you need.

**Comment by ndossche** [comment] 2023-05-16 20:12
I did find the problem, first breakage is at https://www.dekamer.be/doc/PCRI/html/55/ip230x.html
The HTML structure changed: the question number and title are modelled differently in HTML...

**Comment by LoganDupont** [comment] 2023-08-04 13:09
I was wondering if this will get fixt in the near future. It would be very handy for the elections in 2024

**Comment by ndossche** [comment] 2023-08-04 16:17
OK, I wrote the parsing code for the new format, committed that to the dev branch. And suddenly I get a failure in an old meeting with the old parsing code. I wonder if this is because of a change in dekamer webpages, or if I introduced a regression...
I'll have to take an even deeper look.
I hope I can get this done quickly

**Comment by ndossche** [comment] 2023-08-04 19:07
On the development branch the scrape completed successfully, but I notice the vote data is missing, so I'll have to check why that is.

**Comment by LoganDupont** [comment] 2023-08-04 19:20
No problem, just take your time. I'm already happy someone is looking into it and really appreciate what you are doing!

**Comment by ndossche** [comment] 2023-08-04 22:03
I think I got it working for all cases.
I pushed everything to the main branch and the scrape finished.
Now we just have to wait until the CDN caching picks up the changed files.
I'll check tomorrow if everything looks OK.

**Comment by ndossche** [comment] 2023-08-05 11:50
Cached data is updated, and it seems to work correctly.
Closing this as resolved.

**Closed as completed by ndossche** 2023-08-05 11:50 UTC
Labels: bug, important
