### ISSUE TITLE
[BUG] Scraper didn't scrape plenary meetings starting from 27/10/22

### ISSUE THREAD

**Issue by LoganDupont** [Parliament-in-Data/Federal-Parliament-Scraper#51] opened 2022-11-26 11:52 UTC
**Describe the bug**
It seems there is again an issue with the scraper. If we go to https://parlement.thundr.be/sessions/55/session.json you will see that the last plenary meeting is id 210 with date 2022-10-20T00:00:00. Normally there should be a new one with id 211 from 27/10/22.

**To Reproduce**
1. Go to https://parlement.thundr.be/sessions/55/session.json
2. Click on `meetings.plenary[0]`
3. You will see the most recent plenary meeting that has been scraped (https://parlement.thundr.be/sessions/55/meetings/210.json)

**Expected behavior**
I would expect to see the most recent plenary meeting that has happened

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 107.0

**Smartphone (please complete the following information):**
/

**Additional context**
/

**Comment by ndossche** [comment] 2022-11-26 13:37
I've made sure all meetings up until nr 217 are now scraped (https://parlement.thundr.be/sessions/55/meetings/217.json)
The old [session list](https://parlement.thundr.be/sessions/55/session.json) is likely still cached by Cloudflare's CDN, but that cache should also update very soon. If you need the latest version of the session list right now, you can always use a cache-busting trick like adding a query parameter: https://parlement.thundr.be/sessions/55/session.json?a=a
I'll recheck this evening if the cache is updated correctly, and if so I'll close it then.

**Comment by ndossche** [comment] 2022-11-26 20:47
The cache has been updated and the website correctly displays all the meetings now.

**Closed as completed by ndossche** 2022-11-26 20:47 UTC
Labels: bug, important

**Comment by LoganDupont** [comment] 2022-11-27 18:45
@nielsdos Thank you for fixing this again. Any idea why this is happening each time after some weeks? Just wondering what is causing this problem.

**Comment by ndossche** [comment] 2022-11-27 19:38
#48 was caused by downtime of our hosting (Netlify)
#49 was caused both by a change in the HTML layout of the meeting report *and* a mistake in the reporting. We rely on the fixed structure of the HTML files to extract information, therefore a layout change messes with the scraper. These things are rather unpredictable unfortunately but luckily don't happen too often.
#50 was caused by Cloudflare's caching that didn't update in time.

And finally, this issue was caused by GitHub actions having stopped the workflow due to inactivity in the repository. It appears that GitHub pauses your workflows if there haven't been commits to any branches of a repository for a while. To fix it, I've re-enabled the workflows and set up a reminder so I catch this type of issue earlier.

So there are a variety of reasons why the scraping stops after a while. The two hosting related issues are somewhat out of our control. The meeting report layout issues are unpredictable and have to be handled by debugging the scraper on the failing reports. To catch this earlier, I now get an email if the workflows fail. Finally, the GitHub actions issue shouldn't happen anymore.

**Comment by LoganDupont** [comment] 2022-11-27 20:00
Thank you for the information!
